# Prometheus Configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'monitoring-portal'
    environment: 'production'

# Load and evaluate rules in these files every 'evaluation_interval' seconds.
rule_files:
  - "/etc/prometheus/rules/*.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/prometheus/metrics'
    scrape_interval: 10s

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Traefik metrics
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Keycloak metrics (if JMX enabled)
  # - job_name: 'keycloak'
  #   static_configs:
  #     - targets: ['keycloak:8080']
  #   metrics_path: '/auth/metrics'
  #   scrape_interval: 30s

  # Node Exporter (add if you deploy it)
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
  #   scrape_interval: 15s

  # Docker container metrics (cAdvisor)
  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['cadvisor:8080']
  #   scrape_interval: 15s

  # PostgreSQL metrics (if postgres_exporter deployed)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']
  #   scrape_interval: 30s

  # Custom application metrics
  - job_name: 'webapp'
    static_configs:
      - targets: ['webapp:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Blackbox exporter for endpoint monitoring
  # - job_name: 'blackbox'
  #   metrics_path: /probe
  #   params:
  #     module: [http_2xx]
  #   static_configs:
  #     - targets:
  #       - https://monitor.domain.com/grafana
  #       - https://monitor.domain.com/prometheus
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: __param_target
  #     - source_labels: [__param_target]
  #       target_label: instance
  #     - target_label: __address__
  #       replacement: blackbox-exporter:9115

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093  # Enable if you deploy Alertmanager

# Storage configuration
#storage:
#  tsdb:
#    retention.time: 15d
#    retention.size: 10GB